"""empty message

Revision ID: 07be70f8c82c
Revises: e35308d2b362
Create Date: 2024-02-01 12:42:22.723664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07be70f8c82c'
down_revision = 'e35308d2b362'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
